FROM python:3.9-slim-buster

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential gcc python3-dev libopenblas-dev libgomp1 swig && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Копируем зависимости и устанавливаем их
COPY requirements.txt .
RUN pip install --no-cache-dir -U pip && \
    pip install --no-cache-dir -r requirements.txt

# Копируем код приложения и данные
COPY . .
# теперь внутри контейнера есть /app/data/train.csv

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
