version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: web_service/Dockerfile.fastapi
    container_name: backend
    networks:
      - app-network
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models

  frontend:
    build:
      context: .
      dockerfile: web_service/Dockerfile.streamlit
    container_name: frontend
    networks:
      - app-network
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./logs:/app/logs

networks:
  app-network:
    driver: bridge
